# Don't modify this file, it is only needed for the pipeline to set the image and ingressHost
java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
    rpts:
      secrets:
        - name: api-POSTGRES-PASS
          alias: POSTGRES_PASSWORD
        - name: api-POSTGRES-USER
          alias: POSTGRES_USERNAME
        - name: api-POSTGRES-HOST
          alias: POSTGRES_HOST
        - name: api-POSTGRES-DATABASE
          alias: POSTGRES_DATABASE
        - name: api-POSTGRES-PORT
          alias: POSTGRES_PORT
        - name: app-insights-connection-string
          alias: app-insights-connection-string
