spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:11://localhost:4001/functionalTest
    username: javapostgres
    password: javapassword
  config:
    import: optional:configtree:/mnt/secrets/rpts/

server:
  port: 4001

os:
  key: ${OS_KEY}
  url: https://api.os.uk/search/places/v1
  endpoint:
    postcode-search: /postcode
