version: '2.1'

services:
  rpts-api:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/spring-boot/template
    environment:
      # these environment variables are used by java-logging library
      - ROOT_APPENDER
      - JSON_CONSOLE_PRETTY_PRINT
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_TYPE
      - REFORM_SERVICE_NAME
      - REFORM_TEAM
      - REFORM_ENVIRONMENT
      - LOGBACK_DATE_FORMAT
      - LOGBACK_REQUIRE_THREAD
      - LOGBACK_REQUIRE_ALERT_LEVEL=false
      - LOGBACK_REQUIRE_ERROR_CODE=false
    ports:
      - $SERVER_PORT:$SERVER_PORT
  rpts-database:
    build:
      context: docker/database
    environment:
      POSTGRES_DB: rpts
      POSTGRES_USER: rpts
      POSTGRES_PASSWORD: rpts
    ports:
      - 5432:5432
    volumes:
      - rpts-database:/var/lib/postgresql/data

volumes:
  rpts-database:
