server:
  port: 4000

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

springdoc:
  packagesToScan: uk.gov.hmcts.reform.rpts.controllers

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  config:
    import: "optional:configtree:/mnt/secrets/"
  application:
    name: Spring Boot Template
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:rpts}${DB_OPTIONS:}
    username: ${POSTGRES_USER:rpts}
    password: ${POSTGRES_PASSWORD:rpts}
    properties:
      charSet: UTF-8
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 10000
      poolName: RPTSHikariCP
      maxLifetime: 7200000
      connectionTimeout: 30000
  flyway:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:rpts}${DB_OPTIONS:}
    password: ${POSTGRES_PASSWORD}
    user: ${POSTGRES_USER}
    baseline-on-migrate: true
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        jdbc:
          lob:
            non_contextual_creation: true

hibernate:
  show_sql=true:

dbMigration:
  runOnStartup: ${RUN_DB_MIGRATION_ON_STARTUP:true}


