SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- Add tables
-- 1) ONS National Statistics Postcode Lookup (NSPL)
-- 2) ONS Code History Database
CREATE TABLE public.nspl(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pcd VARCHAR (9) NOT NULL,
    pcd2 VARCHAR (9) NOT NULL,
    pcds VARCHAR (9) NOT NULL,
    dointr INTEGER NOT NULL,
    doterm VARCHAR (6) DEFAULT 0,
    usertype INTEGER NOT NULL,
    oseast1m VARCHAR (6) DEFAULT 0 NOT NULL,
    osnrth1m VARCHAR (7) DEFAULT 0 NOT NULL,
    osgrdind INTEGER NOT NULL,
    oa11 VARCHAR (10) NOT NULL,
    cty VARCHAR (9) NOT NULL,
    ced VARCHAR (9) NOT NULL,
    laua VARCHAR (9) NOT NULL,
    ward VARCHAR (9) NOT NULL,
    hlthau VARCHAR (9) NOT NULL,
    nhser VARCHAR (9) NOT NULL,
    ctry VARCHAR (9) NOT NULL,
    rgn VARCHAR (9) NOT NULL,
    pcon VARCHAR (9) NOT NULL,
    eer VARCHAR (9) NOT NULL,
    teclec VARCHAR (9) NOT NULL,
    ttwa VARCHAR (9) NOT NULL,
    pct VARCHAR (9) NOT NULL,
    itl VARCHAR (9) NOT NULL,
    park VARCHAR (9) NOT NULL,
    lsoa11 VARCHAR (9) NOT NULL,
    msoa11 VARCHAR (9) NOT NULL,
    wz11 VARCHAR (9) NOT NULL,
    ccg VARCHAR (9) NOT NULL,
    bua11 VARCHAR (9) NOT NULL,
    buasd11 VARCHAR (9) NOT NULL,
    ru11ind	VARCHAR (2) DEFAULT 0 NOT NULL,
    oac11 VARCHAR (3) NOT NULL,
    lat DOUBLE PRECISION,
    long DOUBLE PRECISION,
    lep1 VARCHAR (9) NOT NULL,
    lep2 VARCHAR (9) NOT NULL,
    pfa VARCHAR (9) NOT NULL,
    imd INTEGER NOT NULL,
    calncv VARCHAR (9) NOT NULL,
    stp VARCHAR (9) NOT NULL
);

CREATE TABLE public.nspl_history(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    GEOGCD VARCHAR (9) NOT NULL,
    GEOGNM VARCHAR (100),
    GEOGNMW VARCHAR (50),
    GEOGCDO VARCHAR (50),
    GEOGNMO VARCHAR (100),
    GEOGCDD VARCHAR (6),
    GEOGNMD VARCHAR (50),
    GEOGCDH VARCHAR (10),
    GEOGNMH VARCHAR (100),
    GEOGCDS VARCHAR (10),
    GEOGNMS VARCHAR (100),
    GEOGCDI VARCHAR (10),
    GEOGNMI VARCHAR (10),
    GEOGCDWG VARCHAR (10),
    GEOGNMWG VARCHAR (50),
    GEOGNMWWG VARCHAR (50),
    OPER_DATE VARCHAR (20),
    TERM_DATE VARCHAR (20),
    ENTITYCD VARCHAR (10),
    YEAR VARCHAR(4),
    STATUS VARCHAR (10)
);
